server:
  port: 8940
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.1.113.173:3306/elastic-batch
    username: root
    password: root
  batch:
    job:
      enabled: false
    initializer:
      enabled: true
      
      
regCenter:
  serverList: 127.0.0.1:2181
  namespace: demo
      
simpleJob:
  cron: 1/20 * * * * ?
  shardingTotalCount: 5
  shardingItemParameters: 0=0,1=1,2=2,3=3,4=4
  name: DEMO-JOB
  description: 通用分片任务
  
path:
  csvfilepath: D:\\WorkspaceAll\\SpringBatch\\SpringBatch-Demo\\src\\main\\resources\\in.csv
  